version: '3'
services:
    app:
        build: .
        container_name: "app"
        depends_on:
            - db
        environment:
            - FLASK_APP=run.py
            - SECRET_KEY=Your_secret_string
            - APP_SETTINGS=development
            - YOUTUBE_API_KEY=AIzaSyBZk38K69wz_GrArKNJhOr5wpS2JD-mseA
            - MYSQL_DATABASE=youtuber
            - MYSQL_USER=youtuber
            - MYSQL_PASSWORD=change_this
        external_links:
            - db:database
        ports:
            - 5000:5000
            - 8080:8080
        entrypoint:
          - "/bin/start.sh"
        volumes:
            - ./frontend:/home/api/frontend
            - ./api:/home/api/backend
        tty: true
        stdin_open: true

    db:
        image: mysql:5.7
        restart: always
        container_name: "mysql"
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=change_this
            - MYSQL_DATABASE=youtuber
            - MYSQL_USER=youtuber
            - MYSQL_PASSWORD=change_this