version: '3'
services:
    db:
        image: mysql
        restart: always
        container_name: "mysql"
        ports:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=change_this
            - MYSQL_DATABASE=youtuber
            - MYSQL_USER=youtuber
            - MYSQL_PASSWORD=change_this