"""empty message

Revision ID: 4398f614a2fe
Revises: 8108a125b61a
Create Date: 2018-03-06 22:10:24.197730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4398f614a2fe'
down_revision = '8108a125b61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('views_median', sa.Integer(), nullable=True))
    op.drop_column('channel', 'views_media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('views_media', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('channel', 'views_median')
    # ### end Alembic commands ###
