"""empty message

Revision ID: 8108a125b61a
Revises: 57755e9ff581
Create Date: 2018-03-05 22:50:35.219787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8108a125b61a'
down_revision = '57755e9ff581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('views_media', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'views_media')
    # ### end Alembic commands ###
