"""empty message

Revision ID: 85b9e4257448
Revises: 
Create Date: 2018-03-03 19:27:45.402789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b9e4257448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('youtube_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_index('channel_youtube_id', 'channel', ['youtube_id'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'video_id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('video')
    op.drop_table('tag')
    op.drop_index('channel_youtube_id', table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
