"""empty message

Revision ID: a9e7abe86338
Revises: aedff07c17bd
Create Date: 2018-03-04 18:27:37.533552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e7abe86338'
down_revision = 'aedff07c17bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('first_hour_views', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('video', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('views_on_creation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'views_on_creation')
    op.drop_column('video', 'views')
    op.drop_column('video', 'time_updated')
    op.drop_column('video', 'time_created')
    op.drop_column('video', 'published_at')
    op.drop_column('video', 'first_hour_views')
    # ### end Alembic commands ###
