"""empty message

Revision ID: ca89626dd497
Revises: 
Create Date: 2018-03-05 20:08:31.914482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca89626dd497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_index('tag_name', 'tag', ['name'], unique=True)
    op.create_table('video',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('first_hour_views', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_table('statistic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(length=20), nullable=True),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'video_id'),
    mysql_DEFAULT_CHARSET='utf8',
    mysql_COLLATE='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('statistic')
    op.drop_table('video')
    op.drop_index('tag_name', table_name='tag')
    op.drop_table('tag')
    op.drop_table('channel')
    # ### end Alembic commands ###
