"""empty message

Revision ID: ce520fc2fde8
Revises: 85b9e4257448
Create Date: 2018-03-03 19:31:33.353068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce520fc2fde8'
down_revision = '85b9e4257448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('video', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('video', sa.Column('youtube_id', sa.String(length=20), nullable=True))
    op.create_index('video_youtube_id', 'video', ['youtube_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('video_youtube_id', table_name='video')
    op.drop_column('video', 'youtube_id')
    op.drop_column('video', 'name')
    op.drop_column('video', 'description')
    # ### end Alembic commands ###
