"""empty message

Revision ID: ff8917fce65a
Revises: a9e7abe86338
Create Date: 2018-03-05 00:22:46.054814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8917fce65a'
down_revision = 'a9e7abe86338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tag_name', 'tag', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag_name', table_name='tag')
    # ### end Alembic commands ###
